# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Robert Stacy Lois II/Desktop/aes-256-gcm/wrapper2/top-level-test/top-level-test/top-level-test.srcs/sources_1/ip/axis_upsizer/axis_upsizer.xci
# IP: The module: 'axis_upsizer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Robert Stacy Lois II/Desktop/aes-256-gcm/wrapper2/top-level-test/top-level-test/top-level-test.gen/sources_1/ip/axis_upsizer/axis_upsizer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_upsizer'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Robert Stacy Lois II/Desktop/aes-256-gcm/wrapper2/top-level-test/top-level-test/top-level-test.srcs/sources_1/ip/axis_upsizer/axis_upsizer.xci
# IP: The module: 'axis_upsizer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Robert Stacy Lois II/Desktop/aes-256-gcm/wrapper2/top-level-test/top-level-test/top-level-test.gen/sources_1/ip/axis_upsizer/axis_upsizer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_upsizer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
