# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Robert Stacy Lois II/Desktop/aes-256-gcm/wrapper2/receiver/top-test/top-test/top-test.srcs/sources_1/ip/axis_downsizer/axis_downsizer.xci
# IP: The module: 'axis_downsizer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Robert Stacy Lois II/Desktop/aes-256-gcm/wrapper2/receiver/top-test/top-test/top-test.gen/sources_1/ip/axis_downsizer/axis_downsizer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_downsizer'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Robert Stacy Lois II/Desktop/aes-256-gcm/wrapper2/receiver/top-test/top-test/top-test.srcs/sources_1/ip/axis_downsizer/axis_downsizer.xci
# IP: The module: 'axis_downsizer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Robert Stacy Lois II/Desktop/aes-256-gcm/wrapper2/receiver/top-test/top-test/top-test.gen/sources_1/ip/axis_downsizer/axis_downsizer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_downsizer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
